# Step 5 - merge `domain_data` & 4 external datasets

In [1]:
from shapely.geometry import Point
import geopandas as gpd
import pandas as pd
import ast

## 1. Add 'sa2_code' & 'sa2_name' to `domain_data`, using the shape file `VIC_SA2`

### 1.1 Add 2 features 'sa2_code' & 'sa2_name' to `domain_data`

import `domain_data` & the shape file `VIC_SA2`

In [2]:
domain_data = pd.read_csv('../data/curated/domain_data/domain_data.csv')
VIC_SA2 = gpd.read_file('../data/landing/external_data/shapefile/SA2_2021_AUST_SHP_GDA2020/SA2_2021_AUST_GDA2020.shp')

overview of 2 datasets

In [3]:
domain_data

,postcode,name,rental_price,coordinates,num_parking,desc,num_bedroom,num_bathroom
0,3149.0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,"[-37.8832957, 145.1090502]",1.0,Sienna Simpson,2,1
1,3149.0,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,"[-37.8956779, 145.1171243]",2.0,Matthew Swinnerton,4,3
2,3149.0,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,"[-37.8749788, 145.1117625]",1.0,"data-testid=""nbn-connection_description""><spa...",2,1
3,3149.0,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,"[-37.8832957, 145.1090502]",2.0,Register now to view this stunning two bedroom...,2,1
4,3149.0,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,"[-37.860802, 145.148173]",2.0,PHONE CARMEN MOSS ON 0412 74 99 30 TO INSPECT,3,1
...,...,...,...,...,...,...,...,...
8797,3081.0,1/19 Law Street Heidelberg Heights VIC 3081,550.0,"[-37.7449638, 145.0484437]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,1
8798,3081.0,64 Tobruk Avenue Heidelberg West VIC 3081,500.0,"[-37.7472529, 145.038464]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,1
8799,3081.0,8 Disney Street Heidelberg Heights VIC 3081,680.0,"[-37.7493478, 145.0478948]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,3
8800,3081.0,4B Katoomba Court Heidelberg West VIC 3081,600.0,"[-37.73547670000001, 145.0376889]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,1
8801,3081.0,81 Southern Road Heidelberg Heights VIC 3081,630.0,"[-37.7426578, 145.0507977]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,3

In [4]:
VIC_SA2

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
0,101021007,Braidwood,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,3418.3525,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.58424 -35.44426, 149.58444 -35.4..."
1,101021008,Karabar,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,6.9825,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.21899 -35.36738, 149.21800 -35.3..."
2,101021009,Queanbeyan,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,4.7620,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.21326 -35.34325, 149.21619 -35.3..."
3,101021010,Queanbeyan - East,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,13.0032,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.24034 -35.34781, 149.24024 -35.3..."
4,101021012,Queanbeyan West - Jerrabomberra,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,13.6748,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.19572 -35.36126, 149.19970 -35.3..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2468,901031003,Jervis Bay,0,No change,90103,Jervis Bay,901,Other Territories,9OTER,Other Territories,9,Other Territories,AUS,Australia,67.2296,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"MULTIPOLYGON (((150.69567 -35.18295, 150.69556..."
2469,901041004,Norfolk Island,0,No change,90104,Norfolk Island,901,Other Territories,9OTER,Other Territories,9,Other Territories,AUS,Australia,38.6510,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"MULTIPOLYGON (((167.96325 -29.07212, 167.96326..."
2470,997979799,Migratory - Offshore - Shipping (OT),0,No change,99797,Migratory - Offshore - Shipping (OT),997,Migratory - Offshore - Shipping (OT),99799,Migratory - Offshore - Shipping (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/SA2/...,None
2471,999999499,No usual address (OT),0,No change,99999,No usual address (OT),999,No usual address (OT),99499,No usual address (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/SA2/...,None
2472,ZZZZZZZZZ,Outside Australia,1,New,ZZZZZ,Outside Australia,ZZZ,Outside Australia,ZZZZZ,Outside Australia,Z,Outside Australia,ZZZ,Outside Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/SA2/...,None

simple preprocessing for `VIC_SA2`

In [5]:
VIC_SA2 = gpd.GeoDataFrame(VIC_SA2)

# only keep the data for the Victoria
VIC_SA2 = VIC_SA2[VIC_SA2['STE_NAME21'] == 'Victoria']
# create a JSON
VIC_SA2 = VIC_SA2[['SA2_CODE21', 'SA2_NAME21', 'geometry']]

VIC_SA2.reset_index(drop=True, inplace=True)

In [6]:
VIC_SA2

,SA2_CODE21,SA2_NAME21,geometry
0,201011001,Alfredton,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5..."
1,201011002,Ballarat,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5..."
2,201011005,Buninyong,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6..."
3,201011006,Delacombe,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5..."
4,201011007,Smythes Creek,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6..."
...,...,...,...
519,217041478,Moyne - West,"MULTIPOLYGON (((142.00870 -38.41715, 142.00876..."
520,217041479,Warrnambool - North,"POLYGON ((142.43668 -38.35544, 142.43658 -38.3..."
521,217041480,Warrnambool - South,"POLYGON ((142.45281 -38.39126, 142.45230 -38.3..."
522,297979799,Migratory - Offshore - Shipping (Vic.),None
523,299999499,No usual address (Vic.),None

rename 2 features for readability

In [7]:
VIC_SA2.rename(columns={'SA2_CODE21': 'sa2_code'}, inplace=True)
VIC_SA2.rename(columns={'SA2_NAME21': 'sa2_name'}, inplace=True)

In [8]:
VIC_SA2

,sa2_code,sa2_name,geometry
0,201011001,Alfredton,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5..."
1,201011002,Ballarat,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5..."
2,201011005,Buninyong,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6..."
3,201011006,Delacombe,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5..."
4,201011007,Smythes Creek,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6..."
...,...,...,...
519,217041478,Moyne - West,"MULTIPOLYGON (((142.00870 -38.41715, 142.00876..."
520,217041479,Warrnambool - North,"POLYGON ((142.43668 -38.35544, 142.43658 -38.3..."
521,217041480,Warrnambool - South,"POLYGON ((142.45281 -38.39126, 142.45230 -38.3..."
522,297979799,Migratory - Offshore - Shipping (Vic.),None
523,299999499,No usual address (Vic.),None

change the data type of 'sa2_code' from string type to int type

In [9]:
print(VIC_SA2['sa2_code'].apply(type))

0      <class 'str'>
1      <class 'str'>
2      <class 'str'>
3      <class 'str'>
4      <class 'str'>
           ...
519    <class 'str'>
520    <class 'str'>
521    <class 'str'>
522    <class 'str'>
523    <class 'str'>
Name: sa2_code, Length: 524, dtype: object

In [10]:
VIC_SA2['sa2_code'] = VIC_SA2['sa2_code'].astype(int)
print(VIC_SA2['sa2_code'].apply(type))

0      <class 'int'>
1      <class 'int'>
2      <class 'int'>
3      <class 'int'>
4      <class 'int'>
           ...
519    <class 'int'>
520    <class 'int'>
521    <class 'int'>
522    <class 'int'>
523    <class 'int'>
Name: sa2_code, Length: 524, dtype: object

define a function which can convert 'coordinates' to point geometry

In [11]:
def convert_to_point(coord_str):
    # covert string datatype to a real python list
    coord_list = ast.literal_eval(coord_str)
    
    # create and return point object
    return Point(coord_list[1], coord_list[0])

apply the function to the feature 'coordinates'

In [12]:
domain_data['property_geometry'] = domain_data['coordinates'].apply(convert_to_point)
domain_data_gdf = gpd.GeoDataFrame(domain_data, geometry='property_geometry')
domain_data_gdf.head()

,postcode,name,rental_price,coordinates,num_parking,desc,num_bedroom,num_bathroom,property_geometry
0,3149.0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,"[-37.8832957, 145.1090502]",1.0,Sienna Simpson,2,1,POINT (145.10905 -37.88330)
1,3149.0,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,"[-37.8956779, 145.1171243]",2.0,Matthew Swinnerton,4,3,POINT (145.11712 -37.89568)
2,3149.0,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,"[-37.8749788, 145.1117625]",1.0,"data-testid=""nbn-connection_description""><spa...",2,1,POINT (145.11176 -37.87498)
3,3149.0,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,"[-37.8832957, 145.1090502]",2.0,Register now to view this stunning two bedroom...,2,1,POINT (145.10905 -37.88330)
4,3149.0,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,"[-37.860802, 145.148173]",2.0,PHONE CARMEN MOSS ON 0412 74 99 30 TO INSPECT,3,1,POINT (145.14817 -37.86080)

check if the 2 geometry objects in `domain_data_gdf` & `VIC_SA2` have the same datatype

In [13]:
domain_data_gdf.set_crs(VIC_SA2.crs, inplace=True)

,postcode,name,rental_price,coordinates,num_parking,desc,num_bedroom,num_bathroom,property_geometry
0,3149.0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,"[-37.8832957, 145.1090502]",1.0,Sienna Simpson,2,1,POINT (145.10905 -37.88330)
1,3149.0,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,"[-37.8956779, 145.1171243]",2.0,Matthew Swinnerton,4,3,POINT (145.11712 -37.89568)
2,3149.0,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,"[-37.8749788, 145.1117625]",1.0,"data-testid=""nbn-connection_description""><spa...",2,1,POINT (145.11176 -37.87498)
3,3149.0,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,"[-37.8832957, 145.1090502]",2.0,Register now to view this stunning two bedroom...,2,1,POINT (145.10905 -37.88330)
4,3149.0,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,"[-37.860802, 145.148173]",2.0,PHONE CARMEN MOSS ON 0412 74 99 30 TO INSPECT,3,1,POINT (145.14817 -37.86080)
...,...,...,...,...,...,...,...,...,...
8797,3081.0,1/19 Law Street Heidelberg Heights VIC 3081,550.0,"[-37.7449638, 145.0484437]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,1,POINT (145.04844 -37.74496)
8798,3081.0,64 Tobruk Avenue Heidelberg West VIC 3081,500.0,"[-37.7472529, 145.038464]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,1,POINT (145.03846 -37.74725)
8799,3081.0,8 Disney Street Heidelberg Heights VIC 3081,680.0,"[-37.7493478, 145.0478948]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,3,POINT (145.04789 -37.74935)
8800,3081.0,4B Katoomba Court Heidelberg West VIC 3081,600.0,"[-37.73547670000001, 145.0376889]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,1,POINT (145.03769 -37.73548)
8801,3081.0,81 Southern Road Heidelberg Heights VIC 3081,630.0,"[-37.7426578, 145.0507977]",2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3,3,POINT (145.05080 -37.74266)

Add features about sa2 to `domain_data` based on the relationship of the property coordinates to the sa2 boundary

In [14]:
domain_data = gpd.sjoin(domain_data_gdf, VIC_SA2, how="left", op="within")

/home/zyyin1/.local/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3448: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

In [15]:
domain_data.head()

,postcode,name,rental_price,coordinates,num_parking,desc,num_bedroom,num_bathroom,property_geometry,index_right,sa2_code,sa2_name
0,3149.0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,"[-37.8832957, 145.1090502]",1.0,Sienna Simpson,2,1,POINT (145.10905 -37.88330),388.0,212051324.0,Mount Waverley - South
1,3149.0,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,"[-37.8956779, 145.1171243]",2.0,Matthew Swinnerton,4,3,POINT (145.11712 -37.89568),388.0,212051324.0,Mount Waverley - South
2,3149.0,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,"[-37.8749788, 145.1117625]",1.0,"data-testid=""nbn-connection_description""><spa...",2,1,POINT (145.11176 -37.87498),388.0,212051324.0,Mount Waverley - South
3,3149.0,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,"[-37.8832957, 145.1090502]",2.0,Register now to view this stunning two bedroom...,2,1,POINT (145.10905 -37.88330),388.0,212051324.0,Mount Waverley - South
4,3149.0,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,"[-37.860802, 145.148173]",2.0,PHONE CARMEN MOSS ON 0412 74 99 30 TO INSPECT,3,1,POINT (145.14817 -37.86080),387.0,212051323.0,Mount Waverley - North

add the feature 'sa2_geometry' to `domain_data`

In [16]:
domain_data = pd.merge(domain_data, VIC_SA2[['sa2_code', 'geometry']], on='sa2_code', how='left')

# rename the sa2 boundary geometry in `VIC_SA2` & `domain_data`
VIC_SA2.rename(columns={'geometry': 'sa2_geometry'}, inplace=True)
domain_data.rename(columns={'geometry': 'sa2_geometry'}, inplace=True)

# delete unnecessary index column
domain_data.drop(columns=['index_right'], inplace=True)

In [17]:
domain_data.head()

,postcode,name,rental_price,coordinates,num_parking,desc,num_bedroom,num_bathroom,property_geometry,sa2_code,sa2_name,sa2_geometry
0,3149.0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,"[-37.8832957, 145.1090502]",1.0,Sienna Simpson,2,1,POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
1,3149.0,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,"[-37.8956779, 145.1171243]",2.0,Matthew Swinnerton,4,3,POINT (145.11712 -37.89568),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
2,3149.0,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,"[-37.8749788, 145.1117625]",1.0,"data-testid=""nbn-connection_description""><spa...",2,1,POINT (145.11176 -37.87498),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
3,3149.0,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,"[-37.8832957, 145.1090502]",2.0,Register now to view this stunning two bedroom...,2,1,POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
4,3149.0,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,"[-37.860802, 145.148173]",2.0,PHONE CARMEN MOSS ON 0412 74 99 30 TO INSPECT,3,1,POINT (145.14817 -37.86080),212051323.0,Mount Waverley - North,"POLYGON ((145.11274 -37.86250, 145.11300 -37.8..."

### 1.2 Reorder the `domain_data` for readability

In [18]:
new_order = [
    'name', 'rental_price', 'num_bedroom', 'num_bathroom', 'num_parking', 'desc', 
    'postcode', 'coordinates', 'property_geometry', 'sa2_code', 'sa2_name', 'sa2_geometry'
]
domain_data = domain_data[new_order]

In [19]:
domain_data.head()

,name,rental_price,num_bedroom,num_bathroom,num_parking,desc,postcode,coordinates,property_geometry,sa2_code,sa2_name,sa2_geometry
0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,2,1,1.0,Sienna Simpson,3149.0,"[-37.8832957, 145.1090502]",POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
1,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,4,3,2.0,Matthew Swinnerton,3149.0,"[-37.8956779, 145.1171243]",POINT (145.11712 -37.89568),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
2,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,2,1,1.0,"data-testid=""nbn-connection_description""><spa...",3149.0,"[-37.8749788, 145.1117625]",POINT (145.11176 -37.87498),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
3,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,2,1,2.0,Register now to view this stunning two bedroom...,3149.0,"[-37.8832957, 145.1090502]",POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
4,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,3,1,2.0,PHONE CARMEN MOSS ON 0412 74 99 30 TO INSPECT,3149.0,"[-37.860802, 145.148173]",POINT (145.14817 -37.86080),212051323.0,Mount Waverley - North,"POLYGON ((145.11274 -37.86250, 145.11300 -37.8..."

### 1.3 Store `domain_data` to `data/curated/domain_data/`

In [20]:
output_directory = '../../real-estate-industry-project-open-source-industry-project-22/data/curated/domain_data/domain_data.csv'
domain_data.to_csv(output_directory, index=False)

In [21]:
'''
output_directory = '../../real-estate-industry-project-open-source-industry-project-22/data/test/domain_data_test.csv'
domain_data.to_csv(output_directory, index=False)
'''

"\noutput_directory = '../../real-estate-industry-project-open-source-industry-project-22/data/test/domain_data_test.csv'\ndomain_data.to_csv(output_directory, index=False)\n"

## 2. Create the dataset `postcode_sa2_relationship`, which describes the relationship between postcodes & sa2

### 2.1 create `postcode_sa2_relationship`

In [22]:
postcode_sa2_relationship = domain_data[['postcode', 'sa2_code', 'sa2_name']]
postcode_sa2_relationship

      postcode     sa2_code                sa2_name
0       3149.0  212051324.0  Mount Waverley - South
1       3149.0  212051324.0  Mount Waverley - South
2       3149.0  212051324.0  Mount Waverley - South
3       3149.0  212051324.0  Mount Waverley - South
4       3149.0  212051323.0  Mount Waverley - North
...        ...          ...                     ...
8797    3081.0  209011199.0         Heidelberg West
8798    3081.0  209011199.0         Heidelberg West
8799    3081.0  209011199.0         Heidelberg West
8800    3081.0  209011199.0         Heidelberg West
8801    3081.0  209011199.0         Heidelberg West

[8802 rows x 3 columns]

In [23]:
postcode_sa2_relationship = postcode_sa2_relationship.drop_duplicates().reset_index(drop=True)
postcode_sa2_relationship

     postcode     sa2_code                   sa2_name
0      3149.0  212051324.0     Mount Waverley - South
1      3149.0  212051323.0     Mount Waverley - North
2      3550.0  202011020.0  East Bendigo - Kennington
3      3550.0  202011018.0                    Bendigo
4      3550.0  202011021.0  Flora Hill - Spring Gully
..        ...          ...                        ...
449    3037.0  213041575.0                   Hillside
450    3037.0  213011339.0                   Sydenham
451    3037.0  213041360.0               Taylors Hill
452    3037.0  213011331.0                    Delahey
453    3081.0  209011199.0            Heidelberg West

[454 rows x 3 columns]

### 2.2 Store `postcode_sa2_relationship` to `data/curated/external_data/`

In [24]:
output_directory = '../../real-estate-industry-project-open-source-industry-project-22/data/curated/external_data/postcode_sa2_relationship.csv'
postcode_sa2_relationship.to_csv(output_directory, index=False)

In [25]:
'''
output_directory = '../../real-estate-industry-project-open-source-industry-project-22/data/test/postcode_sa2_relationship.csv'
postcode_sa2_relationship.to_csv(output_directory, index=False)
'''

"\noutput_directory = '../../real-estate-industry-project-open-source-industry-project-22/data/test/postcode_sa2_relationship.csv'\npostcode_sa2_relationship.to_csv(output_directory, index=False)\n"

## 3. Create the dataset `sa2_info`, using the 4 external datasets

In [26]:
VIC_SA2

,sa2_code,sa2_name,sa2_geometry
0,201011001,Alfredton,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5..."
1,201011002,Ballarat,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5..."
2,201011005,Buninyong,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6..."
3,201011006,Delacombe,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5..."
4,201011007,Smythes Creek,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6..."
...,...,...,...
519,217041478,Moyne - West,"MULTIPOLYGON (((142.00870 -38.41715, 142.00876..."
520,217041479,Warrnambool - North,"POLYGON ((142.43668 -38.35544, 142.43658 -38.3..."
521,217041480,Warrnambool - South,"POLYGON ((142.45281 -38.39126, 142.45230 -38.3..."
522,297979799,Migratory - Offshore - Shipping (Vic.),None
523,299999499,No usual address (Vic.),None

### 3.1 Create `sa2_info` by merging `VIC_SA2` & `avg_personal_income`

import the external dataset `personal_income`

In [27]:
avg_personal_income = pd.read_csv('../data/curated/external_data/personal_income.csv')

overview of `avg_personal_income`

In [28]:
avg_personal_income

,SA2,SA2 NAME,2021-22,average_annual_income_growth_rate(%)
0,201011001,Alfredton,70221.678422,3.315147
1,201011002,Ballarat,81692.230896,1.966376
2,201011003,Ballarat - North,66174.399262,3.251032
3,201011004,Ballarat - South,55723.392324,3.194337
4,201011005,Buninyong,67670.251419,2.518041
...,...,...,...,...
457,217031476,Otway,50982.507858,3.114070
458,217041477,Moyne - East,65554.609008,5.709545
459,217041478,Moyne - West,62307.670624,3.644015
460,217041479,Warrnambool - North,62887.945438,3.753438
461,217041480,Warrnambool - South,62855.296524,3.570089

merge to create `sa2_info`

In [29]:
sa2_info = VIC_SA2 \
    .merge(
        avg_personal_income[['SA2', '2021-22', 'average_annual_income_growth_rate(%)']], 
        left_on = 'sa2_code', 
        right_on = 'SA2', 
        how = 'left'
    ).drop('SA2', axis=1)

sa2_info.rename(columns={'2021-22': 'personal_income'}, inplace=True)
sa2_info.rename(columns={'average_annual_income_growth_rate(%)': 'avg_income_growth_rate(%)'}, inplace=True)

In [30]:
sa2_info

,sa2_code,sa2_name,sa2_geometry,personal_income,avg_income_growth_rate(%)
0,201011001,Alfredton,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5...",70221.678422,3.315147
1,201011002,Ballarat,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5...",81692.230896,1.966376
2,201011005,Buninyong,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6...",67670.251419,2.518041
3,201011006,Delacombe,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5...",59944.622956,3.329186
4,201011007,Smythes Creek,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6...",66511.506655,4.190462
...,...,...,...,...,...
519,217041478,Moyne - West,"MULTIPOLYGON (((142.00870 -38.41715, 142.00876...",62307.670624,3.644015
520,217041479,Warrnambool - North,"POLYGON ((142.43668 -38.35544, 142.43658 -38.3...",62887.945438,3.753438
521,217041480,Warrnambool - South,"POLYGON ((142.45281 -38.39126, 142.45230 -38.3...",62855.296524,3.570089
522,297979799,Migratory - Offshore - Shipping (Vic.),None,NaN,NaN
523,299999499,No usual address (Vic.),None,NaN,NaN

### 3.2 Merge `sa2_info` & `population`

import the external dataset `predicated_pop`

In [31]:
population = pd.read_csv('../data/curated/external_data/predicated_pop.csv')

overview of `population`

In [32]:
population

,SA2_NAME,2021,2022,2023,2024,2025,2026,avg_growth_rates(%)
0,Alfredton,16841,18067.281057,19382.854034,20794.220743,22308.356423,23932.744220,7.281522
1,Ballarat,12071,12025.743532,11980.656739,11935.738985,11890.989636,11846.408061,-0.374919
2,Buninyong,7229,7213.223879,7197.482187,7181.774849,7166.101789,7150.462933,-0.218234
3,Delacombe,10648,11517.284118,12457.535072,13474.546472,14574.584905,15764.428555,8.163825
4,Smythes Creek,4211,4256.693634,4302.883090,4349.573749,4396.771049,4444.480488,1.085102
...,...,...,...,...,...,...,...,...
517,Otway,3979,4069.484476,4162.026614,4256.673208,4353.472113,4452.472275,2.274051
518,Moyne - East,6990,7047.691724,7105.859605,7164.507573,7223.639589,7283.259650,0.825347
519,Moyne - West,9967,10041.496567,10116.549946,10192.164298,10268.343816,10345.092724,0.747432
520,Warrnambool - North,22470,22681.582416,22895.157137,23110.742925,23328.358716,23548.023624,0.941622
521,Warrnambool - South,13298,13323.207785,13348.463355,13373.766799,13399.118208,13424.517674,0.189561

merge `sa2_info` & `population`

In [33]:
sa2_info = sa2_info \
    .merge(population[['SA2_NAME', '2021', 'avg_growth_rates(%)']], left_on='sa2_name', right_on='SA2_NAME', how = 'left') \
    .drop('SA2_NAME', axis=1)

sa2_info.rename(columns={'2021': '2021_population'}, inplace=True)
sa2_info.rename(columns={'avg_growth_rates(%)': 'avg_pop_growth_rates(%)'}, inplace=True)

In [34]:
sa2_info

,sa2_code,sa2_name,sa2_geometry,personal_income,avg_income_growth_rate(%),2021_population,avg_pop_growth_rates(%)
0,201011001,Alfredton,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5...",70221.678422,3.315147,16841.0,7.281522
1,201011002,Ballarat,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5...",81692.230896,1.966376,12071.0,-0.374919
2,201011005,Buninyong,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6...",67670.251419,2.518041,7229.0,-0.218234
3,201011006,Delacombe,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5...",59944.622956,3.329186,10648.0,8.163825
4,201011007,Smythes Creek,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6...",66511.506655,4.190462,4211.0,1.085102
...,...,...,...,...,...,...,...
519,217041478,Moyne - West,"MULTIPOLYGON (((142.00870 -38.41715, 142.00876...",62307.670624,3.644015,9967.0,0.747432
520,217041479,Warrnambool - North,"POLYGON ((142.43668 -38.35544, 142.43658 -38.3...",62887.945438,3.753438,22470.0,0.941622
521,217041480,Warrnambool - South,"POLYGON ((142.45281 -38.39126, 142.45230 -38.3...",62855.296524,3.570089,13298.0,0.189561
522,297979799,Migratory - Offshore - Shipping (Vic.),None,NaN,NaN,NaN,NaN
523,299999499,No usual address (Vic.),None,NaN,NaN,NaN,NaN

### 3.3 Merge `sa2_info` & `sa2_crime_rate`

#### 2.3.1 Convert `postcode_crime_count` to `sa2_crime_count`

import the external dataset `Crime`, this contains crime count based on postcodes

In [35]:
postcode_crime_cont = pd.read_csv('../data/curated/external_data/Crime.csv')

overview of `postcode_crime_cont` & `postcode_sa2_relationship`

In [36]:
postcode_crime_cont

     postcode  crime_count
0        3000    86.666667
1        3002    55.666667
2        3003    54.666667
3        3004   118.666667
4        3006   117.333333
..        ...          ...
688      3990     2.333333
689      3991    21.666667
690      3992    30.333333
691      3995   169.333333
692      3996    39.666667

[693 rows x 2 columns]

In [37]:
postcode_sa2_relationship

     postcode     sa2_code                   sa2_name
0      3149.0  212051324.0     Mount Waverley - South
1      3149.0  212051323.0     Mount Waverley - North
2      3550.0  202011020.0  East Bendigo - Kennington
3      3550.0  202011018.0                    Bendigo
4      3550.0  202011021.0  Flora Hill - Spring Gully
..        ...          ...                        ...
449    3037.0  213041575.0                   Hillside
450    3037.0  213011339.0                   Sydenham
451    3037.0  213041360.0               Taylors Hill
452    3037.0  213011331.0                    Delahey
453    3081.0  209011199.0            Heidelberg West

[454 rows x 3 columns]

add the 'crime_count' based on postcode, to each postcode in `postcode_sa2_relationship`, then call it `sa2_crime_cont`

Assumption: we assume the several sa2's under a postcode have the same crime rate, I will mention it again later.

In [38]:
sa2_crime_cont = postcode_sa2_relationship.merge(postcode_crime_cont, on="postcode", how="left")
sa2_crime_cont.rename(columns={'crime_count': 'postcode_crime_count'}, inplace=True)

In [39]:
sa2_crime_cont

     postcode     sa2_code                   sa2_name  postcode_crime_count
0      3149.0  212051324.0     Mount Waverley - South             53.666667
1      3149.0  212051323.0     Mount Waverley - North             53.666667
2      3550.0  202011020.0  East Bendigo - Kennington            441.000000
3      3550.0  202011018.0                    Bendigo            441.000000
4      3550.0  202011021.0  Flora Hill - Spring Gully            441.000000
..        ...          ...                        ...                   ...
449    3037.0  213041575.0                   Hillside            201.333333
450    3037.0  213011339.0                   Sydenham            201.333333
451    3037.0  213041360.0               Taylors Hill            201.333333
452    3037.0  213011331.0                    Delahey            201.333333
453    3081.0  209011199.0            Heidelberg West            138.333333

[454 rows x 4 columns]

#### 2.3.2 Convert `sa2_crime_cont` to `sa2_crime_rate`

overview of `population`

In [40]:
population

,SA2_NAME,2021,2022,2023,2024,2025,2026,avg_growth_rates(%)
0,Alfredton,16841,18067.281057,19382.854034,20794.220743,22308.356423,23932.744220,7.281522
1,Ballarat,12071,12025.743532,11980.656739,11935.738985,11890.989636,11846.408061,-0.374919
2,Buninyong,7229,7213.223879,7197.482187,7181.774849,7166.101789,7150.462933,-0.218234
3,Delacombe,10648,11517.284118,12457.535072,13474.546472,14574.584905,15764.428555,8.163825
4,Smythes Creek,4211,4256.693634,4302.883090,4349.573749,4396.771049,4444.480488,1.085102
...,...,...,...,...,...,...,...,...
517,Otway,3979,4069.484476,4162.026614,4256.673208,4353.472113,4452.472275,2.274051
518,Moyne - East,6990,7047.691724,7105.859605,7164.507573,7223.639589,7283.259650,0.825347
519,Moyne - West,9967,10041.496567,10116.549946,10192.164298,10268.343816,10345.092724,0.747432
520,Warrnambool - North,22470,22681.582416,22895.157137,23110.742925,23328.358716,23548.023624,0.941622
521,Warrnambool - South,13298,13323.207785,13348.463355,13373.766799,13399.118208,13424.517674,0.189561

add the 'population' based on sa2, to each sa2 in `sa2_crime_cont`

In [41]:
sa2_crime_cont = sa2_crime_cont \
    .merge(population[['SA2_NAME', '2021']], left_on='sa2_name', right_on='SA2_NAME', how = 'left') \
    .drop('SA2_NAME', axis=1)

sa2_crime_cont.rename(columns={'2021': '2021_population'}, inplace=True)

In [42]:
sa2_crime_cont

,postcode,sa2_code,sa2_name,postcode_crime_count,2021_population
0,3149.0,212051324.0,Mount Waverley - South,53.666667,19471.0
1,3149.0,212051323.0,Mount Waverley - North,53.666667,16238.0
2,3550.0,202011020.0,East Bendigo - Kennington,441.000000,13930.0
3,3550.0,202011018.0,Bendigo,441.000000,14955.0
4,3550.0,202011021.0,Flora Hill - Spring Gully,441.000000,9419.0
...,...,...,...,...,...
449,3037.0,213041575.0,Hillside,201.333333,16346.0
450,3037.0,213011339.0,Sydenham,201.333333,11859.0
451,3037.0,213041360.0,Taylors Hill,201.333333,19794.0
452,3037.0,213011331.0,Delahey,201.333333,8148.0
453,3081.0,209011199.0,Heidelberg West,138.333333,15039.0

group by 'postcode' to calculate the population under each postcode

In [43]:
postcode_pop = sa2_crime_cont.groupby('postcode', sort=False)['2021_population'].sum()
postcode_pop = postcode_pop.reset_index()
postcode_pop.rename(columns={'2021_population': 'postcode_population'}, inplace=True)

In [44]:
postcode_pop

     postcode  postcode_population
0      3149.0              35709.0
1      3550.0              52756.0
2      3171.0              22515.0
3      3058.0              60019.0
4      3020.0              48089.0
..        ...                  ...
176    3124.0              37381.0
177    3076.0              33827.0
178    3165.0              30917.0
179    3037.0              56147.0
180    3081.0              15039.0

[181 rows x 2 columns]

add 'postcode_population' to `sa2_crime_cont`, then call this df `sa2_crime_rate`

In [45]:
sa2_crime_rate = sa2_crime_cont[['postcode', 'sa2_code', 'sa2_name', 'postcode_crime_count']].merge(postcode_pop, on='postcode', how = 'left')
sa2_crime_rate

,postcode,sa2_code,sa2_name,postcode_crime_count,postcode_population
0,3149.0,212051324.0,Mount Waverley - South,53.666667,35709.0
1,3149.0,212051323.0,Mount Waverley - North,53.666667,35709.0
2,3550.0,202011020.0,East Bendigo - Kennington,441.000000,52756.0
3,3550.0,202011018.0,Bendigo,441.000000,52756.0
4,3550.0,202011021.0,Flora Hill - Spring Gully,441.000000,52756.0
...,...,...,...,...,...
449,3037.0,213041575.0,Hillside,201.333333,56147.0
450,3037.0,213011339.0,Sydenham,201.333333,56147.0
451,3037.0,213041360.0,Taylors Hill,201.333333,56147.0
452,3037.0,213011331.0,Delahey,201.333333,56147.0
453,3081.0,209011199.0,Heidelberg West,138.333333,15039.0

calculate sa2 crime rate by using 'postcode_crime_count' & 'postcode_population'

Assumption: we assume the several sa2's under a postcode have the same crime rate.

In [46]:
sa2_crime_rate['crime_rate(%)'] = sa2_crime_rate['postcode_crime_count'] / sa2_crime_rate['postcode_population'] * 100

In [47]:
sa2_crime_rate

,postcode,sa2_code,sa2_name,postcode_crime_count,postcode_population,crime_rate(%)
0,3149.0,212051324.0,Mount Waverley - South,53.666667,35709.0,0.150289
1,3149.0,212051323.0,Mount Waverley - North,53.666667,35709.0,0.150289
2,3550.0,202011020.0,East Bendigo - Kennington,441.000000,52756.0,0.835924
3,3550.0,202011018.0,Bendigo,441.000000,52756.0,0.835924
4,3550.0,202011021.0,Flora Hill - Spring Gully,441.000000,52756.0,0.835924
...,...,...,...,...,...,...
449,3037.0,213041575.0,Hillside,201.333333,56147.0,0.358583
450,3037.0,213011339.0,Sydenham,201.333333,56147.0,0.358583
451,3037.0,213041360.0,Taylors Hill,201.333333,56147.0,0.358583
452,3037.0,213011331.0,Delahey,201.333333,56147.0,0.358583
453,3081.0,209011199.0,Heidelberg West,138.333333,15039.0,0.919831

then we found that some postcodes have the same sa2

In [48]:
unique_count = sa2_crime_rate['sa2_name'].nunique()
print(unique_count)

356

For a recurring 'sa2_name', average the crime rate for it.

In [49]:
sa2_crime_rate = sa2_crime_rate.groupby(['sa2_code', 'sa2_name'], sort=False)['crime_rate(%)'].mean().reset_index()

In [50]:
sa2_crime_rate

        sa2_code                   sa2_name  crime_rate(%)
0    212051324.0     Mount Waverley - South       0.150289
1    212051323.0     Mount Waverley - North       0.150289
2    202011020.0  East Bendigo - Kennington       0.835924
3    202011018.0                    Bendigo       0.835924
4    202011021.0  Flora Hill - Spring Gully       0.835924
..           ...                        ...            ...
351  209041431.0              Epping - East       0.180329
352  209041432.0             Epping - South       0.180329
353  213041575.0                   Hillside       0.358583
354  213011339.0                   Sydenham       0.358583
355  213011331.0                    Delahey       0.358583

[356 rows x 3 columns]

#### 2.3.3 Merge `sa2_info` & `sa2_crime_rate`

In [51]:
sa2_info

,sa2_code,sa2_name,sa2_geometry,personal_income,avg_income_growth_rate(%),2021_population,avg_pop_growth_rates(%)
0,201011001,Alfredton,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5...",70221.678422,3.315147,16841.0,7.281522
1,201011002,Ballarat,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5...",81692.230896,1.966376,12071.0,-0.374919
2,201011005,Buninyong,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6...",67670.251419,2.518041,7229.0,-0.218234
3,201011006,Delacombe,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5...",59944.622956,3.329186,10648.0,8.163825
4,201011007,Smythes Creek,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6...",66511.506655,4.190462,4211.0,1.085102
...,...,...,...,...,...,...,...
519,217041478,Moyne - West,"MULTIPOLYGON (((142.00870 -38.41715, 142.00876...",62307.670624,3.644015,9967.0,0.747432
520,217041479,Warrnambool - North,"POLYGON ((142.43668 -38.35544, 142.43658 -38.3...",62887.945438,3.753438,22470.0,0.941622
521,217041480,Warrnambool - South,"POLYGON ((142.45281 -38.39126, 142.45230 -38.3...",62855.296524,3.570089,13298.0,0.189561
522,297979799,Migratory - Offshore - Shipping (Vic.),None,NaN,NaN,NaN,NaN
523,299999499,No usual address (Vic.),None,NaN,NaN,NaN,NaN

In [52]:
sa2_info = sa2_info.merge(sa2_crime_rate[['sa2_code', 'crime_rate(%)']], on='sa2_code', how = 'left')

In [53]:
sa2_info

,sa2_code,sa2_name,sa2_geometry,personal_income,avg_income_growth_rate(%),2021_population,avg_pop_growth_rates(%),crime_rate(%)
0,201011001,Alfredton,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5...",70221.678422,3.315147,16841.0,7.281522,0.602187
1,201011002,Ballarat,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5...",81692.230896,1.966376,12071.0,-0.374919,0.476385
2,201011005,Buninyong,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6...",67670.251419,2.518041,7229.0,-0.218234,0.602187
3,201011006,Delacombe,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5...",59944.622956,3.329186,10648.0,8.163825,0.327216
4,201011007,Smythes Creek,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6...",66511.506655,4.190462,4211.0,1.085102,NaN
...,...,...,...,...,...,...,...,...
519,217041478,Moyne - West,"MULTIPOLYGON (((142.00870 -38.41715, 142.00876...",62307.670624,3.644015,9967.0,0.747432,NaN
520,217041479,Warrnambool - North,"POLYGON ((142.43668 -38.35544, 142.43658 -38.3...",62887.945438,3.753438,22470.0,0.941622,0.252553
521,217041480,Warrnambool - South,"POLYGON ((142.45281 -38.39126, 142.45230 -38.3...",62855.296524,3.570089,13298.0,0.189561,0.252553
522,297979799,Migratory - Offshore - Shipping (Vic.),None,NaN,NaN,NaN,NaN,NaN
523,299999499,No usual address (Vic.),None,NaN,NaN,NaN,NaN,NaN

### 3.4 Store `sa2_info` to `data/curated/external_data/`

In [54]:
output_directory = '../../real-estate-industry-project-open-source-industry-project-22/data/curated/external_data/sa2_info.csv'
sa2_info.to_csv(output_directory, index=False)

## 4. Merge `domain_data` & `sa2_info` to create `merged_data`

### 4.1 Create `merged_data`

In [55]:
domain_data.head()

,name,rental_price,num_bedroom,num_bathroom,num_parking,desc,postcode,coordinates,property_geometry,sa2_code,sa2_name,sa2_geometry
0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,2,1,1.0,Sienna Simpson,3149.0,"[-37.8832957, 145.1090502]",POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
1,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,4,3,2.0,Matthew Swinnerton,3149.0,"[-37.8956779, 145.1171243]",POINT (145.11712 -37.89568),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
2,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,2,1,1.0,"data-testid=""nbn-connection_description""><spa...",3149.0,"[-37.8749788, 145.1117625]",POINT (145.11176 -37.87498),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
3,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,2,1,2.0,Register now to view this stunning two bedroom...,3149.0,"[-37.8832957, 145.1090502]",POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8..."
4,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,3,1,2.0,PHONE CARMEN MOSS ON 0412 74 99 30 TO INSPECT,3149.0,"[-37.860802, 145.148173]",POINT (145.14817 -37.86080),212051323.0,Mount Waverley - North,"POLYGON ((145.11274 -37.86250, 145.11300 -37.8..."

In [56]:
selected_feature_list = [
    'sa2_name', 'personal_income', 'avg_income_growth_rate(%)', '2021_population', 'avg_pop_growth_rates(%)', 'crime_rate(%)'
]

merged_data = domain_data \
    .merge(sa2_info[selected_feature_list], on='sa2_name', how = 'left')

In [57]:
merged_data

,name,rental_price,num_bedroom,num_bathroom,num_parking,desc,postcode,coordinates,property_geometry,sa2_code,sa2_name,sa2_geometry,personal_income,avg_income_growth_rate(%),2021_population,avg_pop_growth_rates(%),crime_rate(%)
0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,2,1,1.0,Sienna Simpson,3149.0,"[-37.8832957, 145.1090502]",POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8...",70558.093250,2.309177,19471.0,0.200434,0.150289
1,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,4,3,2.0,Matthew Swinnerton,3149.0,"[-37.8956779, 145.1171243]",POINT (145.11712 -37.89568),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8...",70558.093250,2.309177,19471.0,0.200434,0.150289
2,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,2,1,1.0,"data-testid=""nbn-connection_description""><spa...",3149.0,"[-37.8749788, 145.1117625]",POINT (145.11176 -37.87498),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8...",70558.093250,2.309177,19471.0,0.200434,0.150289
3,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,2,1,2.0,Register now to view this stunning two bedroom...,3149.0,"[-37.8832957, 145.1090502]",POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8...",70558.093250,2.309177,19471.0,0.200434,0.150289
4,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,3,1,2.0,PHONE CARMEN MOSS ON 0412 74 99 30 TO INSPECT,3149.0,"[-37.860802, 145.148173]",POINT (145.14817 -37.86080),212051323.0,Mount Waverley - North,"POLYGON ((145.11274 -37.86250, 145.11300 -37.8...",69105.052663,1.936026,16238.0,0.238825,0.150289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8797,1/19 Law Street Heidelberg Heights VIC 3081,550.0,3,1,2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3081.0,"[-37.7449638, 145.0484437]",POINT (145.04844 -37.74496),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444
8798,64 Tobruk Avenue Heidelberg West VIC 3081,500.0,3,1,2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3081.0,"[-37.7472529, 145.038464]",POINT (145.03846 -37.74725),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444
8799,8 Disney Street Heidelberg Heights VIC 3081,680.0,3,3,2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3081.0,"[-37.7493478, 145.0478948]",POINT (145.04789 -37.74935),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444
8800,4B Katoomba Court Heidelberg West VIC 3081,600.0,3,1,2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3081.0,"[-37.73547670000001, 145.0376889]",POINT (145.03769 -37.73548),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444
8801,81 Southern Road Heidelberg Heights VIC 3081,630.0,3,3,2.0,"class=""css-dxogle"">* Unverified feature<svg a...",3081.0,"[-37.7426578, 145.0507977]",POINT (145.05080 -37.74266),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444

### 4.2 Simple preprocessing for `merged_data`

drop the feature 'desc' from `merged_data`, because we thought this feature has no useful information to extract

In [58]:
merged_data.drop(columns=['desc'], inplace=True)

calculate victorial average 'personal_income' & 'income_growth_rate' to fill NaN in `merged_data`

In [59]:
sa2_info.head()

,sa2_code,sa2_name,sa2_geometry,personal_income,avg_income_growth_rate(%),2021_population,avg_pop_growth_rates(%),crime_rate(%)
0,201011001,Alfredton,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5...",70221.678422,3.315147,16841.0,7.281522,0.602187
1,201011002,Ballarat,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5...",81692.230896,1.966376,12071.0,-0.374919,0.476385
2,201011005,Buninyong,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6...",67670.251419,2.518041,7229.0,-0.218234,0.602187
3,201011006,Delacombe,"POLYGON ((143.75050 -37.59119, 143.75044 -37.5...",59944.622956,3.329186,10648.0,8.163825,0.327216
4,201011007,Smythes Creek,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6...",66511.506655,4.190462,4211.0,1.085102,NaN

In [60]:
vic_avg_personal_income = sa2_info['personal_income'].mean()
merged_data['personal_income'].fillna(vic_avg_personal_income, inplace=True)

In [61]:
vic_avg_income_growth_rate = sa2_info['avg_income_growth_rate(%)'].mean()
merged_data['avg_income_growth_rate(%)'].fillna(vic_avg_income_growth_rate, inplace=True)

fill NaN in the feature 'crime_rate(%)' with 0

In [62]:
merged_data['crime_rate(%)'].fillna(0, inplace=True)

In [63]:
merged_data

,name,rental_price,num_bedroom,num_bathroom,num_parking,postcode,coordinates,property_geometry,sa2_code,sa2_name,sa2_geometry,personal_income,avg_income_growth_rate(%),2021_population,avg_pop_growth_rates(%),crime_rate(%)
0,105/436-442 Huntingdale Road Mount Waverley VI...,525.0,2,1,1.0,3149.0,"[-37.8832957, 145.1090502]",POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8...",70558.093250,2.309177,19471.0,0.200434,0.150289
1,4A Adrienne Crescent Mount Waverley VIC 3149,1.0,4,3,2.0,3149.0,"[-37.8956779, 145.1171243]",POINT (145.11712 -37.89568),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8...",70558.093250,2.309177,19471.0,0.200434,0.150289
2,1/2 Grenfell Rd Mount Waverley VIC 3149,500.0,2,1,1.0,3149.0,"[-37.8749788, 145.1117625]",POINT (145.11176 -37.87498),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8...",70558.093250,2.309177,19471.0,0.200434,0.150289
3,310/436-442 Huntingdale Road Mount Waverley VI...,575.0,2,1,2.0,3149.0,"[-37.8832957, 145.1090502]",POINT (145.10905 -37.88330),212051324.0,Mount Waverley - South,"POLYGON ((145.10836 -37.88581, 145.10854 -37.8...",70558.093250,2.309177,19471.0,0.200434,0.150289
4,2/8 Bennett Avenue Mount Waverley VIC 3149,530.0,3,1,2.0,3149.0,"[-37.860802, 145.148173]",POINT (145.14817 -37.86080),212051323.0,Mount Waverley - North,"POLYGON ((145.11274 -37.86250, 145.11300 -37.8...",69105.052663,1.936026,16238.0,0.238825,0.150289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8797,1/19 Law Street Heidelberg Heights VIC 3081,550.0,3,1,2.0,3081.0,"[-37.7449638, 145.0484437]",POINT (145.04844 -37.74496),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444
8798,64 Tobruk Avenue Heidelberg West VIC 3081,500.0,3,1,2.0,3081.0,"[-37.7472529, 145.038464]",POINT (145.03846 -37.74725),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444
8799,8 Disney Street Heidelberg Heights VIC 3081,680.0,3,3,2.0,3081.0,"[-37.7493478, 145.0478948]",POINT (145.04789 -37.74935),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444
8800,4B Katoomba Court Heidelberg West VIC 3081,600.0,3,1,2.0,3081.0,"[-37.73547670000001, 145.0376889]",POINT (145.03769 -37.73548),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444
8801,81 Southern Road Heidelberg Heights VIC 3081,630.0,3,3,2.0,3081.0,"[-37.7426578, 145.0507977]",POINT (145.05080 -37.74266),209011199.0,Heidelberg West,"POLYGON ((145.03288 -37.74090, 145.03281 -37.7...",64100.398902,3.320164,15039.0,0.331631,0.564444

### 4.3 Store `merged_data` to `data/curated/merged_data/`

In [64]:
output_directory = '../../real-estate-industry-project-open-source-industry-project-22/data/curated/merged_data/merged_data.csv'
merged_data.to_csv(output_directory, index=False)