## Date preprocessing of neighborhood parks and reserves

In [1]:
import geopandas as gpd

# Load the shapefile

shape_data_parks = gpd.read_file('../data/landing/external_data/shapefile/Parks_reserves/ll_gda94/esrishape/whole_of_dataset/victoria/CROWNLAND/PARKRES.shp')

# Display rows of the data
print(shape_data_parks)

      PRIMS_ID                                            NAME  \
0         5144    Wombat - Lerderderg National Park (Proposed)
1         5153              Blackwood Regional Park (Proposed)
2          352                 Yarrara Flora and Fauna Reserve
3         4642  Dookie - Katamatite rail line Bushland Reserve
4         1031                      Lyons H12 Bushland Reserve
...        ...                                             ...
8856      4557                    Stawell H20 Bushland Reserve
8857      2684                Eddington K26 Streamside Reserve
8858      3199                           Marlo Coastal Reserve
8859      5077                                  Anglesea Depot
8860      2021                      Moira H14 Bushland Reserve

                                              AREA_TYPE  \
0     PROPOSED NATIONAL PARKS ACT PARK OR PARK ADDITION
1     REGIONAL PARK - NOT SCHEDULED UNDER NATIONAL P...
2     NATURE CONSERVATION RESERVE - FLORA AND FAUNA ...
3           NATURAL FEATURES RESERVE - BUSHLAND RESERVE
4           NATURAL FEATURES RESERVE - BUSHLAND RESERVE
...                                                 ...
8856        NATURAL FEATURES RESERVE - BUSHLAND RESERVE
8857      NATURAL FEATURES RESERVE - STREAMSIDE RESERVE
8858                                    COASTAL RESERVE
8859                                              OTHER
8860        NATURAL FEATURES RESERVE - BUSHLAND RESERVE

                            NAME_SHORT     AREA_SRC  \
0      Wombat-Lerderderg NP (Proposed)  GIS PARKRES
1              Blackwood RP (Proposed)  GIS PARKRES
2                          Yarrara FFR  GIS PARKRES
3     Dookie - Katamatite rail line BR  GIS PARKRES
4                         Lyons H12 BR  GIS PARKRES
...                                ...          ...
8856                    Stawell H20 BR  GIS PARKRES
8857                 Eddington K26 SSR  GIS PARKRES
8858                   Marlo Coast Res  GIS PARKRES
8859                    Anglesea Depot  GIS PARKRES
8860                      Moira H14 BR  GIS PARKRES

                         MANAGER VEAC_REC                         VEAC_STUDY  \
0                          DEECA       A4  Central West Investigation (2019)
1                          DEECA       C5  Central West Investigation (2019)
2                 Parks Victoria       G1               Mallee Review (1989)
3     Other Government Authority     H121  Box-Ironbark Investigation (2001)
4                 Parks Victoria      H12         South West 1 Review (1983)
...                          ...      ...                                ...
8856              Parks Victoria      H20  Box-Ironbark Investigation (2001)
8857              Parks Victoria       H4  Box-Ironbark Investigation (2001)
8858              Parks Victoria       H1       East Gippsland Review (1986)
8859                       DEECA      NaN              No LCC Recommendation
8860              Parks Victoria      H14               Murray Valley (1985)

                      IUCN  TOTAL_AREA                            POLY_SRC  \
0                      NaN   23732.520  VM PARCEL EDITED WITH 25K FEATURES
1                      NaN    3792.386  VM PARCEL EDITED WITH 25K FEATURES
2                       Ia    2267.804                             HOLDING
3                       IV      70.750  VM PARCEL EDITED WITH 25K FEATURES
4                       IV      21.839  VM PARCEL EDITED WITH 25K FEATURES
...                    ...         ...                                 ...
8856                    IV       4.231  VM PARCEL EDITED WITH 25K FEATURES
8857                   III      24.979  VM PARCEL EDITED WITH 25K FEATURES
8858  Not a Protected Area     588.976  VM PARCEL EDITED WITH 25K FEATURES
8859  Not a Protected Area     362.142                             HOLDING
8860                    IV       0.608  VM PARCEL EDITED WITH 25K FEATURES

      AREATYPEID                                           SRCHNAME  \
0             33         Wombat-Lerderderg National Park (Proposed)
1             30                 Blackwood Regional Park (Proposed)
2             21         YARRARA FFR FLORA AND FAUNA RESERVE F.F.R.
3              9  DOOKIE - KATAMATITE RAIL LINE BR BUSHLAND RESE...
4              9                 LYONS H12 BR BUSHLAND RESERVE B.R.
...          ...                                                ...
8856           9               STAWELL H20 BR BUSHLAND RESERVE B.R.
8857          18         EDDINGTON K26 SSR STREAMSIDE RESERVE SS.R.
8858           1        MARLO COAST RES COASTAL RESERVE COAST. RES.
8859          25                ANGLESEA HEATH ALCOA AGREEMENT AREA
8860           9                 MOIRA H14 BR BUSHLAND RESERVE B.R.

      ESTAB_DATE    LAST_MOD   VERS_DATE  HECTARES      AREASQM  \
0            NaN  2023-08-30  2023-09-11   4922.06  49220574.88
1            NaN  2023-08-31  2023-09-11    119.44   1194383.29
2     1979-05-01  2017-10-02  2023-09-11      1.29     12893.57
3     2002-02-26  2021-04-26  2023-09-11      3.70     37002.18
4     1974-03-05  2012-07-11  2023-09-11     21.16    211581.22
...          ...         ...         ...       ...          ...
8856  2002-02-26  2012-07-11  2023-09-11      4.23     42305.59
8857  1982-08-24  2012-07-11  2023-09-11     24.98    249786.28
8858  1979-05-01  2017-10-02  2023-09-11     29.08    290793.54
8859  2000-11-08  2023-08-10  2023-09-11      2.25     22489.06
8860  1986-09-30  2017-10-02  2023-09-11      0.61      6078.40

                                               geometry
0     MULTIPOLYGON (((144.20859 -37.38932, 144.20864...
1     MULTIPOLYGON (((144.29930 -37.38705, 144.30181...
2     POLYGON ((141.42817 -34.39947, 141.42734 -34.3...
3     POLYGON ((145.69151 -36.19915, 145.69122 -36.1...
4     POLYGON ((141.45112 -38.00732, 141.45025 -38.0...
...                                                 ...
8856  POLYGON ((142.84051 -37.01956, 142.83828 -37.0...
8857  POLYGON ((143.85020 -36.87358, 143.85065 -36.8...
8858  POLYGON ((148.49720 -37.80059, 148.49659 -37.8...
8859  POLYGON ((144.19451 -38.39693, 144.19258 -38.3...
8860  POLYGON ((145.02833 -36.07320, 145.02662 -36.0...

[8861 rows x 19 columns]

## Data preprocessing

In [2]:
# Detect missing values
print(shape_data_parks.isnull().sum())

# Drop or fill missing values
shape_data_parks.dropna(inplace=True)
shape_data_parks

PRIMS_ID        0
NAME            0
AREA_TYPE       0
NAME_SHORT      0
AREA_SRC        0
MANAGER         0
VEAC_REC       97
VEAC_STUDY      0
IUCN          210
TOTAL_AREA      0
POLY_SRC        0
AREATYPEID      0
SRCHNAME        0
ESTAB_DATE    847
LAST_MOD        0
VERS_DATE       0
HECTARES        0
AREASQM         0
geometry        0
dtype: int64

,PRIMS_ID,NAME,AREA_TYPE,NAME_SHORT,AREA_SRC,MANAGER,VEAC_REC,VEAC_STUDY,IUCN,TOTAL_AREA,POLY_SRC,AREATYPEID,SRCHNAME,ESTAB_DATE,LAST_MOD,VERS_DATE,HECTARES,AREASQM,geometry
2,352,Yarrara Flora and Fauna Reserve,NATURE CONSERVATION RESERVE - FLORA AND FAUNA ...,Yarrara FFR,GIS PARKRES,Parks Victoria,G1,Mallee Review (1989),Ia,2267.804,HOLDING,21,YARRARA FFR FLORA AND FAUNA RESERVE F.F.R.,1979-05-01,2017-10-02,2023-09-11,1.29,12893.57,"POLYGON ((141.42817 -34.39947, 141.42734 -34.3..."
3,4642,Dookie - Katamatite rail line Bushland Reserve,NATURAL FEATURES RESERVE - BUSHLAND RESERVE,Dookie - Katamatite rail line BR,GIS PARKRES,Other Government Authority,H121,Box-Ironbark Investigation (2001),IV,70.750,VM PARCEL EDITED WITH 25K FEATURES,9,DOOKIE - KATAMATITE RAIL LINE BR BUSHLAND RESE...,2002-02-26,2021-04-26,2023-09-11,3.70,37002.18,"POLYGON ((145.69151 -36.19915, 145.69122 -36.1..."
4,1031,Lyons H12 Bushland Reserve,NATURAL FEATURES RESERVE - BUSHLAND RESERVE,Lyons H12 BR,GIS PARKRES,Parks Victoria,H12,South West 1 Review (1983),IV,21.839,VM PARCEL EDITED WITH 25K FEATURES,9,LYONS H12 BR BUSHLAND RESERVE B.R.,1974-03-05,2012-07-11,2023-09-11,21.16,211581.22,"POLYGON ((141.45112 -38.00732, 141.45025 -38.0..."
5,3293,Churchill National Park,"NATIONAL PARK - SCHEDULE 2, NATIONAL PARKS ACT",Churchill NP,GIS PARKRES,Parks Victoria,-,No LCC Recommendation,III,271.918,VM PARCEL EDITED WITH 25K FEATURES,6,CHURCHILL NP NATIONAL PARK N.P.,1941-02-12,2012-07-11,2023-09-11,271.92,2719179.95,"POLYGON ((145.26571 -37.94591, 145.27077 -37.9..."
6,5092,Yallock-Bulluk Marine & Coastal Park,"OTHER PARK - SCHEDULE 3, NATIONAL PARKS ACT",Yallock-Bulluk MCP,GIS PARKRES,Parks Victoria,J1,South Gippsland 2 (1982),VI,3205.229,VM PARCEL EDITED WITH 25K FEATURES,1,Yallock-Bulluk Marine and Coastal Park,2021-05-01,2021-04-26,2023-09-11,0.32,3193.19,"POLYGON ((145.65611 -38.67085, 145.65593 -38.6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8855,4710,Great Otway National Park,"NATIONAL PARK - SCHEDULE 2, NATIONAL PARKS ACT",Great Otway NP,GIS PARKRES,Parks Victoria,A1,Angahook-Otway Investigation (2004),II,110353.337,HOLDING,6,GREAT OTWAY NP NATIONAL PARK N.P.,2005-12-11,2019-08-01,2023-09-11,137.48,1374769.07,"POLYGON ((143.23517 -38.74880, 143.23318 -38.7..."
8856,4557,Stawell H20 Bushland Reserve,NATURAL FEATURES RESERVE - BUSHLAND RESERVE,Stawell H20 BR,GIS PARKRES,Parks Victoria,H20,Box-Ironbark Investigation (2001),IV,4.231,VM PARCEL EDITED WITH 25K FEATURES,9,STAWELL H20 BR BUSHLAND RESERVE B.R.,2002-02-26,2012-07-11,2023-09-11,4.23,42305.59,"POLYGON ((142.84051 -37.01956, 142.83828 -37.0..."
8857,2684,Eddington K26 Streamside Reserve,NATURAL FEATURES RESERVE - STREAMSIDE RESERVE,Eddington K26 SSR,GIS PARKRES,Parks Victoria,H4,Box-Ironbark Investigation (2001),III,24.979,VM PARCEL EDITED WITH 25K FEATURES,18,EDDINGTON K26 SSR STREAMSIDE RESERVE SS.R.,1982-08-24,2012-07-11,2023-09-11,24.98,249786.28,"POLYGON ((143.85020 -36.87358, 143.85065 -36.8..."
8858,3199,Marlo Coastal Reserve,COASTAL RESERVE,Marlo Coast Res,GIS PARKRES,Parks Victoria,H1,East Gippsland Review (1986),Not a Protected Area,588.976,VM PARCEL EDITED WITH 25K FEATURES,1,MARLO COAST RES COASTAL RESERVE COAST. RES.,1979-05-01,2017-10-02,2023-09-11,29.08,290793.54,"POLYGON ((148.49720 -37.80059, 148.49659 -37.8..."
8860,2021,Moira H14 Bushland Reserve,NATURAL FEATURES RESERVE - BUSHLAND RESERVE,Moira H14 BR,GIS PARKRES,Parks Victoria,H14,Murray Valley (1985),IV,0.608,VM PARCEL EDITED WITH 25K FEATURES,9,MOIRA H14 BR BUSHLAND RESERVE B.R.,1986-09-30,2017-10-02,2023-09-11,0.61,6078.40,"POLYGON ((145.02833 -36.07320, 145.02662 -36.0..."

In [3]:
#rename the column of 'NAME'
shape_data_parks.rename(columns={'NAME': 'park_reserve_name'}, inplace=True)
shape_data_parks = shape_data_parks[['geometry', 'park_reserve_name']]
# Get the centroids for each location
shape_data_parks['parkreserve_centroid'] = shape_data_parks['geometry'].apply(lambda x: (x.centroid.y, x.centroid.x))
shape_data_parks

/home/ximing/.local/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

,geometry,park_reserve_name,parkreserve_centroid
2,"POLYGON ((141.42817 -34.39947, 141.42734 -34.3...",Yarrara Flora and Fauna Reserve,"(-34.39871618343641, 141.4277580140217)"
3,"POLYGON ((145.69151 -36.19915, 145.69122 -36.1...",Dookie - Katamatite rail line Bushland Reserve,"(-36.19279855152709, 145.6913525993461)"
4,"POLYGON ((141.45112 -38.00732, 141.45025 -38.0...",Lyons H12 Bushland Reserve,"(-38.00526809916923, 141.4488222851275)"
5,"POLYGON ((145.26571 -37.94591, 145.27077 -37.9...",Churchill National Park,"(-37.9501196710711, 145.26037105554607)"
6,"POLYGON ((145.65611 -38.67085, 145.65593 -38.6...",Yallock-Bulluk Marine & Coastal Park,"(-38.670342768622845, 145.65632304326317)"
...,...,...,...
8855,"POLYGON ((143.23517 -38.74880, 143.23318 -38.7...",Great Otway National Park,"(-38.7430781583091, 143.23334295934836)"
8856,"POLYGON ((142.84051 -37.01956, 142.83828 -37.0...",Stawell H20 Bushland Reserve,"(-37.018826260867, 142.8392145934658)"
8857,"POLYGON ((143.85020 -36.87358, 143.85065 -36.8...",Eddington K26 Streamside Reserve,"(-36.87609690460606, 143.8520750755008)"
8858,"POLYGON ((148.49720 -37.80059, 148.49659 -37.8...",Marlo Coastal Reserve,"(-37.79862371036882, 148.49454186755756)"
8860,"POLYGON ((145.02833 -36.07320, 145.02662 -36.0...",Moira H14 Bushland Reserve,"(-36.07296775601402, 145.02748769523046)"

In [4]:
from shapely import wkt

# Assuming the equivalent of 'station_centroid' for parks is 'geometry'
shape_data_parks['parkreserve_centroid'] = shape_data_parks['geometry'].centroid

# Extract the latitude and longitude from the centroids
shape_data_parks['parkreserve_coordinates'] = shape_data_parks['parkreserve_centroid'].apply(lambda geom: [geom.y, geom.x])

# Format the coordinates into the desired string format
shape_data_parks['parkreserve_coordinates'] = shape_data_parks['parkreserve_coordinates'].apply(lambda coords: f"[{coords[0]}, {coords[1]}]")
shape_data_parks

/tmp/ipykernel_123792/2605139969.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  shape_data_parks['parkreserve_centroid'] = shape_data_parks['geometry'].centroid
/home/ximing/.local/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/home/ximing/.local/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/home/ximing/.local/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

,geometry,park_reserve_name,parkreserve_centroid,parkreserve_coordinates
2,"POLYGON ((141.42817 -34.39947, 141.42734 -34.3...",Yarrara Flora and Fauna Reserve,POINT (141.42776 -34.39872),"[-34.39871618343641, 141.4277580140217]"
3,"POLYGON ((145.69151 -36.19915, 145.69122 -36.1...",Dookie - Katamatite rail line Bushland Reserve,POINT (145.69135 -36.19280),"[-36.19279855152709, 145.6913525993461]"
4,"POLYGON ((141.45112 -38.00732, 141.45025 -38.0...",Lyons H12 Bushland Reserve,POINT (141.44882 -38.00527),"[-38.00526809916923, 141.4488222851275]"
5,"POLYGON ((145.26571 -37.94591, 145.27077 -37.9...",Churchill National Park,POINT (145.26037 -37.95012),"[-37.9501196710711, 145.26037105554607]"
6,"POLYGON ((145.65611 -38.67085, 145.65593 -38.6...",Yallock-Bulluk Marine & Coastal Park,POINT (145.65632 -38.67034),"[-38.670342768622845, 145.65632304326317]"
...,...,...,...,...
8855,"POLYGON ((143.23517 -38.74880, 143.23318 -38.7...",Great Otway National Park,POINT (143.23334 -38.74308),"[-38.7430781583091, 143.23334295934836]"
8856,"POLYGON ((142.84051 -37.01956, 142.83828 -37.0...",Stawell H20 Bushland Reserve,POINT (142.83921 -37.01883),"[-37.018826260867, 142.8392145934658]"
8857,"POLYGON ((143.85020 -36.87358, 143.85065 -36.8...",Eddington K26 Streamside Reserve,POINT (143.85208 -36.87610),"[-36.87609690460606, 143.8520750755008]"
8858,"POLYGON ((148.49720 -37.80059, 148.49659 -37.8...",Marlo Coastal Reserve,POINT (148.49454 -37.79862),"[-37.79862371036882, 148.49454186755756]"
8860,"POLYGON ((145.02833 -36.07320, 145.02662 -36.0...",Moira H14 Bushland Reserve,POINT (145.02749 -36.07297),"[-36.07296775601402, 145.02748769523046]"

In [5]:
# save as the CSV file into external_data directory for further use
shape_data_parks.to_csv("../data/raw/external_data/parks_data.csv", index=False)
# Computing counts of parks and reserves
parks_counts = shape_data_parks['park_reserve_name'].value_counts()
print(parks_counts)

park_reserve_name
Great Otway National Park                      153
Otway Forest Park                              151
Bendigo Regional Park                          130
River Murray Reserve                           104
Castlemaine Diggings National Heritage Park     76
                                              ...
Wangie Bushland Reserve                          1
Bontherambo H112 Bushland Reserve                1
Woodend I13 Bushland Reserve                     1
Heywood Bushland Reserve                         1
Moira H14 Bushland Reserve                       1
Name: count, Length: 3270, dtype: int64

In [6]:
# Keep a unique record of each park name
shape_data_parks= shape_data_parks.drop_duplicates(subset=['park_reserve_name'])  

# Extract the desired columns
shape_data_parks = shape_data_parks[['park_reserve_name', 'parkreserve_coordinates']]

# Save the updated data to a CSV file into raw folder for further usage
shape_data_parks.to_csv("../data/raw/external_data/parks_data.csv", index=False)
shape_data_parks

,park_reserve_name,parkreserve_coordinates
2,Yarrara Flora and Fauna Reserve,"[-34.39871618343641, 141.4277580140217]"
3,Dookie - Katamatite rail line Bushland Reserve,"[-36.19279855152709, 145.6913525993461]"
4,Lyons H12 Bushland Reserve,"[-38.00526809916923, 141.4488222851275]"
5,Churchill National Park,"[-37.9501196710711, 145.26037105554607]"
6,Yallock-Bulluk Marine & Coastal Park,"[-38.670342768622845, 145.65632304326317]"
...,...,...
8849,Woranga Bushland Reserve,"[-38.544860697937274, 146.70102582042378]"
8851,Noojee Bushland Reserve,"[-37.90006205421842, 146.00270988884594]"
8856,Stawell H20 Bushland Reserve,"[-37.018826260867, 142.8392145934658]"
8857,Eddington K26 Streamside Reserve,"[-36.87609690460606, 143.8520750755008]"
8860,Moira H14 Bushland Reserve,"[-36.07296775601402, 145.02748769523046]"

## Find the closest park or reserve

In [7]:
import pandas as pd
# read property data and parks data
property_data = pd.read_csv("../data/curated/merged_data/merged_data_with_facility.csv")
parks_data = pd.read_csv("../data/raw/external_data/parks_data.csv")
parks_data = parks_data[['park_reserve_name', 'parkreserve_coordinates']]
parks_data
property_data

,name,rental_price,num_bedroom,num_bathroom,num_parking,postcode,coordinates,property_geometry,sa2_code,sa2_name,...,avg_income_growth_rate(%),2021_population,avg_pop_growth_rates(%),crime_rate(%),closest_school,school_distance(KM),closest_hospital,hospital_distance(KM),closest_mall,mall_distance(KM)
0,31 Chittagong Drive Clyde North VIC 3978,575.0,4,2,2.0,3978.0,"[-38.1053122, 145.3570863]",POINT (145.3570863 -38.1053122),212031556.0,Clyde North - South,...,3.028540,15038.0,129.962525,0.122595,"[-38.10602, 145.37876]",1.898006,"[-38.045325, 145.347181]",6.726397,"[-38.1184718, 145.3213262]",3.453903
1,50 Elmtree Crescent Clyde North VIC 3978,560.0,4,2,2.0,3978.0,"[-38.0825712, 145.3561984]",POINT (145.3561984 -38.0825712),212031555.0,Clyde North - North,...,3.028540,10652.0,29.771333,0.122595,"[-38.08468, 145.3638]",0.705427,"[-38.045325, 145.347181]",4.216162,"[-38.0604189, 145.3394612]",2.866025
2,7 Mortdale Lane Clyde North VIC 3978,490.0,2,2,1.0,3978.0,"[-38.0961758, 145.3800644]",POINT (145.3800644 -38.0961758),212031556.0,Clyde North - South,...,3.028540,15038.0,129.962525,0.122595,"[-38.10602, 145.37876]",1.100561,"[-38.045325, 145.347181]",6.344909,"[-38.0604189, 145.3394612]",5.332842
3,54 Walhallow Drive Clyde North VIC 3978,540.0,4,2,1.0,3978.0,"[-38.1133324, 145.3457396]",POINT (145.3457396 -38.1133324),212031556.0,Clyde North - South,...,3.028540,15038.0,129.962525,0.122595,"[-38.11488, 145.33828]",0.674921,"[-38.113312, 145.280832]",5.678594,"[-38.1184718, 145.3213262]",2.210922
4,10 Sicily Road Clyde North VIC 3978,520.0,4,2,2.0,3978.0,"[-38.1295789, 145.3642993]",POINT (145.3642993 -38.1295789),212031303.0,Cranbourne South,...,2.233051,17641.0,14.250357,0.197962,"[-38.12955, 145.33886]",2.225124,"[-38.113312, 145.280832]",7.522231,"[-38.1184718, 145.3213262]",3.956745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8797,61 Tongue Street Yarraville VIC 3013,630.0,2,1,0.0,3013.0,"[-37.8131463, 144.8909053]",POINT (144.8909053 -37.8131463),213031352.0,Yarraville,...,3.965740,15651.0,0.003162,0.197223,"[-37.8137, 144.8899]",0.107655,"[-37.800508, 144.895155]",1.454065,"[-37.8016476, 144.8977057]",1.411290
8798,47 Mill Avenue Yarraville VIC 3013,730.0,4,3,2.0,3013.0,"[-37.8222822, 144.872198]",POINT (144.872198 -37.8222822),213031352.0,Yarraville,...,3.965740,15651.0,0.003162,0.197223,"[-37.82104, 144.87443]",0.239821,"[-37.797407, 144.887421]",3.072331,"[-37.828989, 144.84627]",2.396280
8799,12 Adeney Street Yarraville VIC 3013,450.0,3,1,2.0,3013.0,"[-37.8163817, 144.8666543]",POINT (144.8666543 -37.8163817),213031352.0,Yarraville,...,3.965740,15651.0,0.003162,0.197223,"[-37.8126, 144.87466]",0.819385,"[-37.797407, 144.887421]",2.789294,"[-37.828989, 144.84627]",2.273966
8800,229B Somerville Road Yarraville VIC 3013,300.0,1,1,0.0,3013.0,"[-37.8124289, 144.8779569]",POINT (144.8779569 -37.8124289),213031352.0,Yarraville,...,3.965740,15651.0,0.003162,0.197223,"[-37.8126, 144.87466]",0.290245,"[-37.797407, 144.887421]",1.865866,"[-37.8016476, 144.8977057]",2.108881
8801,4/185 Francis Street Yarraville VIC 3013,420.0,1,1,2.0,3013.0,"[-37.8206224, 144.8827922]",POINT (144.8827922 -37.8206224),213031352.0,Yarraville,...,3.965740,15651.0,0.003162,0.197223,"[-37.81791, 144.88365]",0.310875,"[-37.800508, 144.895155]",2.486363,"[-37.8016476, 144.8977057]",2.483570

In [8]:
from geopy.distance import great_circle
import numpy as np

# Convert a string formatted as "[latitude, longitude]" into a tuple (latitude, longitude)
def parse_coordinates(coord_str):
    parts = coord_str.strip('[]').split(',')
    return float(parts[0]), float(parts[1])

# Convert string representations of coordinates into actual coordinate tuples
property_coordinates = property_data['coordinates'].apply(parse_coordinates)
park_coordinates = parks_data['parkreserve_coordinates'].apply(parse_coordinates)

# For a given property coordinate, determine the single nearest park and its distance
def find_nearest_park(property_coord):
    if np.isnan(property_coord).any():
        return None, float('inf')  # If invalid property coordinates, return None and infinite distance
    
    distances = [
        great_circle(property_coord, park_coord).kilometers
        if not np.isnan(park_coord).any() else float('inf')
        for park_coord in park_coordinates
    ]
    
    # Identify the index of the closest park
    closest_index = np.argmin(distances)
    
    # Extract the closest park's coordinates
    closest_park = parks_data.loc[closest_index, 'parkreserve_coordinates']
    
    return closest_park, distances[closest_index]

# Compute closest park and its distance for each property
property_data['closest_park'], property_data['park_distance(KM)'] = zip(*property_coordinates.apply(find_nearest_park))

# Display the modified property_data dataframe
property_data

,name,rental_price,num_bedroom,num_bathroom,num_parking,postcode,coordinates,property_geometry,sa2_code,sa2_name,...,avg_pop_growth_rates(%),crime_rate(%),closest_school,school_distance(KM),closest_hospital,hospital_distance(KM),closest_mall,mall_distance(KM),closest_park,park_distance(KM)
0,31 Chittagong Drive Clyde North VIC 3978,575.0,4,2,2.0,3978.0,"[-38.1053122, 145.3570863]",POINT (145.3570863 -38.1053122),212031556.0,Clyde North - South,...,129.962525,0.122595,"[-38.10602, 145.37876]",1.898006,"[-38.045325, 145.347181]",6.726397,"[-38.1184718, 145.3213262]",3.453903,"[-38.13958090963712, 145.36252669303045]",3.840116
1,50 Elmtree Crescent Clyde North VIC 3978,560.0,4,2,2.0,3978.0,"[-38.0825712, 145.3561984]",POINT (145.3561984 -38.0825712),212031555.0,Clyde North - North,...,29.771333,0.122595,"[-38.08468, 145.3638]",0.705427,"[-38.045325, 145.347181]",4.216162,"[-38.0604189, 145.3394612]",2.866025,"[-38.03401014838179, 145.37166338662394]",5.566924
2,7 Mortdale Lane Clyde North VIC 3978,490.0,2,2,1.0,3978.0,"[-38.0961758, 145.3800644]",POINT (145.3800644 -38.0961758),212031556.0,Clyde North - South,...,129.962525,0.122595,"[-38.10602, 145.37876]",1.100561,"[-38.045325, 145.347181]",6.344909,"[-38.0604189, 145.3394612]",5.332842,"[-38.13958090963712, 145.36252669303045]",5.064419
3,54 Walhallow Drive Clyde North VIC 3978,540.0,4,2,1.0,3978.0,"[-38.1133324, 145.3457396]",POINT (145.3457396 -38.1133324),212031556.0,Clyde North - South,...,129.962525,0.122595,"[-38.11488, 145.33828]",0.674921,"[-38.113312, 145.280832]",5.678594,"[-38.1184718, 145.3213262]",2.210922,"[-38.13958090963712, 145.36252669303045]",3.267265
4,10 Sicily Road Clyde North VIC 3978,520.0,4,2,2.0,3978.0,"[-38.1295789, 145.3642993]",POINT (145.3642993 -38.1295789),212031303.0,Cranbourne South,...,14.250357,0.197962,"[-38.12955, 145.33886]",2.225124,"[-38.113312, 145.280832]",7.522231,"[-38.1184718, 145.3213262]",3.956745,"[-38.13958090963712, 145.36252669303045]",1.122928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8797,61 Tongue Street Yarraville VIC 3013,630.0,2,1,0.0,3013.0,"[-37.8131463, 144.8909053]",POINT (144.8909053 -37.8131463),213031352.0,Yarraville,...,0.003162,0.197223,"[-37.8137, 144.8899]",0.107655,"[-37.800508, 144.895155]",1.454065,"[-37.8016476, 144.8977057]",1.411290,"[-37.83084513979606, 144.91345002848863]",2.791844
8798,47 Mill Avenue Yarraville VIC 3013,730.0,4,3,2.0,3013.0,"[-37.8222822, 144.872198]",POINT (144.872198 -37.8222822),213031352.0,Yarraville,...,0.003162,0.197223,"[-37.82104, 144.87443]",0.239821,"[-37.797407, 144.887421]",3.072331,"[-37.828989, 144.84627]",2.396280,"[-37.83084513979606, 144.91345002848863]",3.746179
8799,12 Adeney Street Yarraville VIC 3013,450.0,3,1,2.0,3013.0,"[-37.8163817, 144.8666543]",POINT (144.8666543 -37.8163817),213031352.0,Yarraville,...,0.003162,0.197223,"[-37.8126, 144.87466]",0.819385,"[-37.797407, 144.887421]",2.789294,"[-37.828989, 144.84627]",2.273966,"[-37.83084513979606, 144.91345002848863]",4.413664
8800,229B Somerville Road Yarraville VIC 3013,300.0,1,1,0.0,3013.0,"[-37.8124289, 144.8779569]",POINT (144.8779569 -37.8124289),213031352.0,Yarraville,...,0.003162,0.197223,"[-37.8126, 144.87466]",0.290245,"[-37.797407, 144.887421]",1.865866,"[-37.8016476, 144.8977057]",2.108881,"[-37.83084513979606, 144.91345002848863]",3.729966
8801,4/185 Francis Street Yarraville VIC 3013,420.0,1,1,2.0,3013.0,"[-37.8206224, 144.8827922]",POINT (144.8827922 -37.8206224),213031352.0,Yarraville,...,0.003162,0.197223,"[-37.81791, 144.88365]",0.310875,"[-37.800508, 144.895155]",2.486363,"[-37.8016476, 144.8977057]",2.483570,"[-37.83084513979606, 144.91345002848863]",2.922800

In [9]:
#save the updated file into curated folder 
property_data.to_csv('../data/curated/merged_data/merged_data_with_facility.csv', index=False)

In [10]:
property_data['closest_park'][0]

'[-38.13958090963712, 145.36252669303045]'